# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('inventory', models.PositiveSmallIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('update_date', models.DateTimeField(verbose_name='date updated')),
                ('long_desc', models.CharField(max_length=1000)),
                ('short_desc', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('AI', 'Air Intake'), ('BK', 'Brakes'), ('CL', 'Cooling'), ('DT', 'Drivetrain and Transmission'), ('EC', 'Electronics'), ('EG', 'Engine'), ('EX', 'Exhaust'), ('FC', 'Fuel Components'), ('GH', 'Gauges and Gauge Holders'), ('IG', 'Ignition Components'), ('IC', 'Intercoolers'), ('IT', 'Interior'), ('SL', 'Silicon Couplers and Hoses'), ('SF', 'Safety'), ('SP', 'Suspension'), ('TK', 'Turbochargers and Kits'), ('WG', 'Wastegates'), ('MC', 'Miscellanious'), ('TM', 'Turbocharger accessories and kits')], default='AI', max_length=2)),
            ],
        ),
    ]
